% program for creating the adapted waveform
% for further creating the set of functions basing on it
% 05.10.2004 10-42
% recalled from scr_5

af=figure('Name','Creating the waveset matrix.', ...
        'NumberTitle','off', ...
        'Visible','on');
     set(af,'units','pixels');
     s=get(0,'ScreenSize');
set(af,'position',[.1*s(3) .07*s(4) .8*s(3) .8*s(4)]);
set(af,'doublebuffer','on');
set(af,'renderer','painters');
set(af,'color',[.8  .9 .1]);
clear s;

% close button creation
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.9 .005 .09 .07],'String','Close',...
   'FontWeight','bold','fontsize',10,'Callback','close(gcf)');

% button for creating new
acn=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.01 .9 .45 .04],...
   'String','Create new waveset matrix',...
   'FontWeight','bold','fontsize',10,...
   'Callback',['WSM=zeros(1,wf_end-wf_beg+1);',...
       'WSM=sig(wf_beg:wf_end);',...
       'set([asnb afn],''visible'',''on'')']);

% button for adding to existing
aae=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.48 .9 .51 .04],...
   'String','Add this waveform to existing waveset matrix',...
   'FontWeight','bold','fontsize',10,...
   'Callback',' set([aleb afn],''visible'',''on'') ');

% button for loading
% existing waveset to further create the set
% added 4.12.2004
aue=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.25 .95 .51 .04],'String','Load existing waveset matrix',...
   'FontWeight','bold','fontsize',10,...
   'Callback',' set([aleb afn],''visible'',''on''); set(aleb,''Userdata'',1);');

% text for file name 
afn=uicontrol('Style','edit','Units','normalized',...
   'Position',[.33 .84 .3 .04],'String','',...
   'FontWeight','bold','fontsize',10,...
   'Callback','    ','visible','off',...
   'tooltip','Input the name of file');

% saving the new obtained waveform 
asnb=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.42 .79 .1 .04],'String','Save',...
   'FontWeight','bold','fontsize',10,'visible','off',...
   'Callback','save(get(afn,''string''), ''WSM''); set([fcrs txtc],''visible'',''on'');');

% button for opening existing matrix file,
% and evaluating the adapted waveform!!!!!!!
% !!!!!!!!!!!!!!
aleb=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.42 .79 .1 .04],'String','Load',...
   'FontWeight','bold','fontsize',10,'visible','off',...
   'Callback','adapted_func_1_scr_1;','userdata',0);

% closing and returning tip
txtc=uicontrol('Style','text','Units','normalized',...
   'Position',[.3 .65 .35 .1],'String','If you want to add another one waveform to the set press "Return" button.',...
   'FontWeight','bold','fontsize',10,'visible','off');

% closing and returning 
fcrs=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.3 .6 .35 .04],'String','Return',...
   'FontWeight','bold','fontsize',10,'visible','off',...
   'Callback','close(gcf); ');

% opening existing matrix file 
txt=uicontrol('Style','text','Units','normalized',...
   'Position',[.3 .44 .35 .14],...
   'String','If you want to create the set basing on this newly obtained adapted initial set function press "Create the set" .',...
   'FontWeight','bold','fontsize',10,'visible','off');

% creating the set  
fcs=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.3 .38 .35 .04],'String','Create the set',...
   'FontWeight','bold','fontsize',10,'visible','off',...
   'Callback',...
   'wf_beg=1; wf_end=length(setfun); sig=setfun;  close (gcf); GalileoView_scr_5');
%close (fd1);








