% program for calculating coefficients == projections
% of signal on the overcomplete set of functions
% for using with GalileoView

% 01.06.2005, 18-01

% called from 

f_p=figure('Name','Calculating projections on the set.', ...
        'NumberTitle','off', ...
        'Visible','on');
set(0,'units','normalized');
s=get(0,'ScreenSize');
set(gcf,'units','normalized')
set(gcf,'position',[0.01  0.07    0.97    0.85]); %
set(0,'units','pixels');
clear s;
set(gcf,'renderer','painters');
set(gcf,'color',[1 .8 .6]);

% close button creation
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.9 .005 .09 .04],'String','Close',...
   'FontWeight','bold','fontsize',14,'Callback','close(gcf)');

%axis for signal plot
a3=axes('parent',gcf);
set(a3,'box','on','linewidth',2,'tickdir','in','ticklength',[.01 0.025]...
    ,'units','normalized','position',[.055 .078 .92 .77]);
set(a3,'GridLineStyle',':','xgrid','on','ygrid','on',...
    'fontname','courier','fontsize',10,'FontWeight','bold',...
    'color',[.9 .9 1],'xcolor','black','ycolor','black',...
    'buttondownfcn','');
 
 
% line for detailed plot
sig=A(ln,:);
% !!!!!!
%SIG=sig;% the variable for storing the whole lead, chosen from
% first window % for returning after set forming
l3=line('parent',a3,'linewidth',1,'ydata',sig,...
   'xdata',1:smp_num,...
   'buttondownfcn','',...
   'userdata','');

%TIP text with set function file 
uicontrol('Style','text','Units','normalized',...
   'Position',[.4 .95 .1 .046],'String','Set function file name=>',...
   'FontWeight','bold','fontsize',9,'buttondownfcn','');

% text for filename with setfunction 
sfnt3=uicontrol('style','edit','units','normalized',...
   'position',[.51 .95 .13 .046],'FontWeight','normal','fontsize',12,...
   'createfcn','','callback','');

%button for opening the set from file
uicontrol('style','pushbutton', 'units','normalized','position',[.59 .9 .05 .046],'string','Open',...
    'FontWeight','bold','fontsize',10,...
    'Callback','clear setfunfile ; setfunfile=get(sfnt3,''string''); load(setfunfile)');

% text for inputting the step to move analysis window 
stp=uicontrol('style','edit','units','normalized',...
   'position',[.16 .87 .05 .046],'FontWeight','normal','fontsize',12,...
   'string','1',...
   'TooltipString','Input the step to move analysis window.',...
   'callback','');

% button for processing the selected lead
pb3=uicontrol('style','pushbutton','string','Process',...
   'FontWeight','bold','fontsize',10,...
   'units','normalized',...
   'position',[.22 .855 .08 .09],...
   'callback','set(fpb3,''visible'',''off''); w_stp=str2num(get(stp,''string'')); tic; eeg_patt_loc_scr_1; toc');

% button for further visualizing obtained coefficients
fpb3=uicontrol('style','pushbutton','string','Further process coefficients',...
   'FontWeight','bold','fontsize',10,...
   'units','normalized','visible','off',...
   'position',[.31 .855 .25 .09],...
   'callback','eeg_patt_loc_coef_vis');

% button for opening empty window for 
% visualizing early obtained coefficients
uicontrol('style','pushbutton',...
   'string','View coefficients',...
   'FontWeight','bold','fontsize',10,...
   'units','normalized',...
   'position',[.8 .855 .2 .09],...
   'callback','coef=zeros(1,1); eeg_patt_loc_coef_vis');