% program for manual constructing of
% the filter frequency response for further EEG analysis
% #1 15.08.2005 13-21
% #2 28.08.2005 18-35

%clc
%close all
%clear all;
f=figure('Name','Manual Filter Frequency response composer.', ...
        'NumberTitle','off','Visible','on');
     set(f,'units','pixels');
     s=get(0,'ScreenSize');
set(f,'position',[s(1) .05*s(4) .995*s(3) .88*s(4)]);
set(f,'doublebuffer','on');
set(f,'renderer','painters');
set(f,'color',[.7  .8 .5]);

% close button creation
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.9 .005 .09 .04],'String','Close',...
   'FontWeight','bold','fontsize',10,'Callback','close(gcf)');

% text with tip for number of points
uicontrol('Style','text','Units','normalized',...
   'Position',[.003 .967 .28 .028],'String',...
   'Input Sample Rate (256/128) =>',...
   'FontWeight','normal','fontsize',8,'buttondownfcn','');

% text for number of points 
fn=uicontrol('style','edit','units','normalized',...
   'position',[.285 .96 .05 .038],'FontWeight',...
   'normal','fontsize',8,...
   'callback','','string',256);

% text with tip for increment value
uicontrol('Style','text','Units','normalized',...
   'Position',[.003 .917 .1 .028],'String',...
   'Increment:',...
   'FontWeight','normal','fontsize',8,'buttondownfcn','');

% text for increment 
incc=uicontrol('style','edit','units','normalized',...
   'position',[.11 .91 .05 .038],'FontWeight','normal',...
   'tooltip','Input the frequency step',...
   'fontsize',8,...
   'callback','','string',1);

% text with tip for the value of signal base level (0, 1, 2)
uicontrol('Style','text','Units','normalized',...
   'Position',[.18 .917 .1 .028],'String',...
   'Base:',...
   'FontWeight','normal','fontsize',8,'buttondownfcn','');

% text for base level 
incb=uicontrol('style','edit','units','normalized',...
   'position',[.29 .91 .05 .038],'FontWeight','normal',...
   'tooltip','Input the base level of frequency response ',...
   'fontsize',8,...
   'callback','','string',1);


% button for making the "line template"
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.34 .96 .05 .038],'String','Make',...
   'FontWeight','normal','fontsize',10,...
   'Callback',...
   strcat(...
   'set([sld l fna sw fs],''visible'',''on''); ',...
   'inc=str2num(get(incc,''string''));',...
   'totpts=1+floor(str2num(get(fn,''string''))/inc);',...
   'wave=str2num(get(incb,''string''))*ones(1,totpts);',...
   'set(fs,''sliderstep'',[1 10]/totpts);',...
   'Filter_composer_scr_1;'));

% textbox containing the coordinates of current cursor
% position
cp=uicontrol('style','text','string',...
   int2str(1),'units','normalized','position',[.4 .96 .05 .038],...
   'FontWeight','normal','fontsize',10);

%axis for waveform plot
a=axes('parent',f);
set(a,'box','on','linewidth',3,'tickdir','in','ticklength',[.01 0.025]...
   ,'units','normalized','position',[.045 .2 .6 .7]);
set(a,'GridLineStyle',':','XGrid','on','YGrid','on',...
   'fontname','courier','fontsize',10,'FontWeight','bold',...
   'color',[.9 .9 1],'xcolor','black',...
   'ycolor','black',...
   'ytick',[-.2:.2:3],'ylim',[-.3 3]);

%%%%%%%%%%%%%%

a_len=165; % home PC
% SLIDER for frequency plot
fs=uicontrol('Style','slider','Units','normalized', ...
   'Position',[.045 .1 .6 .04],'visible','off',...
   'Callback','Filter_composer_scr_1');%,...

%making the line "without line"
l=line('parent',a,'linewidth',3, 'buttondownfcn' ,...
   ['D=get(a,''currentpoint'');'...
      'set(cp,''string'',num2str(round(D(1,1))) );'],...
   'visible','off','marker','.','markersize',60);

% slider for increasing/decreasing the values
sld=uicontrol('Style','slider','Units','normalized',...
   'Position',[.66 .37 .06 .35],'max',1,'min',-1, ...
   'SliderStep',[0.01 0.1],'visible','off',...
   'tooltip','Move the slider to increase/decrease current point of Frequency Response.',...
   'callback',strcat(...
   'wave(str2num(get(cp,''string'')))=wave(str2num(get(cp,''string'')))+get(sld,''value'');',...
   'set(gco,''value'',0);',...
   'Filter_composer_scr_1;'...
));

% file name
fna=uicontrol('style','edit','string','',...
   'units','normalized','position',[.702 .79 .13 .05],...
   'FontWeight','normal','fontsize',10,...
   'visible','on',...
   'tooltip','Input the name of file for this waveform.');

% button for saving obtained waveform
sw=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.85 .73 .13 .05],'String','Save FR',...
   'FontWeight','bold','fontsize',10,'visible','off',...
   'Callback','save(get(fna,''string''), ''wave'', ''inc'');');

% button for loading the  waveform
sload=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.85 .79 .13 .05],'String','Load FR',...
   'FontWeight','bold','fontsize',10,'visible','on',...
   'Callback',['clear inc;',...
       'load(get(fna,''string''));'...
       'set([sld l sw fs],''visible'',''on''); '...
       'totpts=length(wave);'...
       'set(fs,''sliderstep'',[1 10]/totpts);',...
       'Filter_composer_scr_1;']);