%script #16 for GalileoView
% 
% called from GalileoView,
% custom filtering of the entire signal
  
% opens new figure for filename with 
% desired Frequency Response
% then performs filtering of the signal (entire!!!)
% 15.08.2005 10-08

figure('Name','Desired Frequency Response', ...
        'NumberTitle','off','units','normalized',...
        'position',[0.15    0.6    0.25    0.2],...
        'color',[0.803    0.5485    0.2618]);
% edit for frequency input
newscale=uicontrol('style','edit','units','normalized',...
   'position',[.1 .7 .4 .2],'FontWeight','normal','fontsize',12,...
   'TooltipString','Type the name of the file with frequency  resconse to filter the current signal and press "Filter It!" button.',...
   'callback','',...
   'string','');


% button for filtering
% and closing the figure
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.1 .45 .4 .2],'String','Filter It!',...
   'FontWeight','light','fontsize',12,...
   'Callback',...
   ['load(get(newscale,''string''));'...
      'cor=zeros(size(A));'...
      'cor=((A(:,smp_num)-A(:,1))/(smp_num-1))*[0:smp_num-1];'...
       'y=zeros([smp_num, ch_num]);'...
       'y=fft(transpose(A-cor));'...
       'spf=zeros(smp_num,1);'...
       'sp=interp1([0:length(wave)-1]*inc,wave,(0:smp_num-1)*SampleRate/smp_num,''nearest'');'...
       'spf(1:round((smp_num-1)/2))=sp(1:round((smp_num-1)/2));'...
       'spf(smp_num:-1:smp_num-round((smp_num-1)/2)+2)=sp(2:round((smp_num-1)/2));'...
       'GalileoView_scr_12;'...
       'A=real(ifft(y)'');'...
       'GalileoView_scr_9;',...
       'clear cor y spf sp inc;'...
       'close(gcf);']);

% for using with MatLAB 6, INTERP1 sould be:
% 'sp=interp1([0:length(wave)-1]*inc,wave,(0:smp_num-1)*SampleRate/smp_num,''nearest'',''extrap'');'...

%       'rt=12%spf(smp_num:-1:smp_num-round((smp_num-1)/2)+2)=sp(2:round((smp_num-1)/2));'...
