%script #11 for GalileoView
% 
% called from GalileoView
%  
% opens new figure for setting custom amplitude scale
% 24.05.2005 9-11

figure('Name','Custom scaling', ...
        'NumberTitle','off','units','normalized','position',[0.15    0.6    0.25    0.2],...
        'color',[0.803    0.5485    0.2618]);
% edit for scale input
newscale=uicontrol('style','edit','units','normalized',...
   'position',[.1 .7 .4 .2],'FontWeight','normal','fontsize',16,...
   'TooltipString','Type the Scale and press "Update" button.',...
   'callback','','string',num2str(50*scale50in1/scale));

% button for updating the scale and closing the figure
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.1 .45 .4 .2],'String','Update',...
   'FontWeight','light','fontsize',14,...
   'Callback', strcat(  'scale=scale50in1*50/str2num(get(newscale,''string''));   ', ...
       'set(scc,''string'',[num2str(50*scale50in1/scale) '' uV/cm '']);   ', ...
       ' GalileoView_scr_18; GalileoView_scr_9;   ' ,...
       'clear newscale; ',...
       'close(gcf);'));