% script #5 for GalileoView
% called from GalileoView_scr_2

% 26.05.2005 18-39

% plots the selected waveform and allows to
% select the limits for function overcomplete set
% creation

% recalled from scr_2 or from wave_composer_1

fwd2=figure('Name',' Overcomplete waveform set creation.', ...
        'NumberTitle','off', ...
        'Visible','off');
     set(fwd2,'units','pixels');
     s=get(0,'ScreenSize');
set(fwd2,'position',[.1*s(3) .07*s(4) .8*s(3) .8*s(4)]);
set(fwd2,'doublebuffer','on');
set(fwd2,'renderer','painters');
set(fwd2,'color',[.5  .6 .6]);
clear s;

% close button creation
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.9 .005 .09 .07],'String','Close',...
   'FontWeight','bold','fontsize',10,'Callback','close(gcf)');

%axis for waveform plot
ad2=axes('parent',fwd2);
set(ad2,'box','on','linewidth',2,'tickdir','in','ticklength',[.01 0.025]...
    ,'units','normalized','position',[0.05 0.31 0.45 0.5]);
set(ad2,'GridLineStyle',':','xgrid','on','ygrid','on',...
    'fontname','courier','fontsize',8,'FontWeight','normal',...
    'color',[.95 1 .9],'xcolor','black','ycolor','black',...
    'buttondownfcn','');

%
%
%
% the chosen waveform
wf=sig(wf_beg:wf_end);% without norming initial function
%
%
%
%
%
% setfunction visualization!!!!!!!!!
lchd2=line('parent',ad2,'linewidth',2); % line for part of lead
% signal, that is selected and shown when figure is created
set(lchd2,'ydata',wf,...
   'xdata',1:wf_end-wf_beg+1);
set(ad2,'xlim',[1 wf_end-wf_beg+1],...
   'xtick',linspace(0,(wf_end-wf_beg+1),5),...
   'xticklabel',linspace(0,(wf_end-wf_beg+1),5),...
   'ylim',[min(wf)-1 max(wf)+1]);


% updated 30.01.2005 15-37:
% the initial function will be shown while setfunctions are
% being vizualized
ll2=line('parent',ad2,'linewidth',2);
%wf_end_init=wf_end;
%wf_beg_init=wf_beg;
set(ll2,'ydata',wf,'xdata',1:wf_end-wf_beg+1,...
   'buttondownfcn','','userdata','');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% text with TIP for parameter ajusting
uicontrol('style','text','units','normalized',...
   'position',[.05 .82 .4 .17],'fontsize',10,...
   'string','Use the number fields for adjusting parameters for scaling, dilating/squeezing and rising/lowing the initial function. Press "OK" button to start forming of the set.');

% buttons for parameter description
%
% Headers
h1=uicontrol('style','text','units','normalized',...
   'position',[.51 .96 .1 .03],'fontsize',10,...
   'string','Parameter');
h2=uicontrol('style','text','units','normalized',...
   'position',[.62 .96 .1 .03],'fontsize',10,...
   'string','Min value');
h3=uicontrol('style','text','units','normalized',...
   'position',[.73 .96 .1 .03],'fontsize',10,...
   'string','Step');
h4=uicontrol('style','text','units','normalized',...
   'position',[.84 .96 .1 .03],'fontsize',10,...
   'string','Max value');

% row for SCALES
sc_b=1;%.95;
sc_s=1;%5e-2;
sc_e=1;%1.05;
sc=[sc_b:sc_s:sc_e];
sc2=uicontrol('style','edit','units','normalized',...
   'position',[.62 .91 .1 .04],'fontsize',10,...
   'string',num2str(sc_b),'createfcn','',...
   'callback','sc_b=str2num(get(gco,''string''));sc=[sc_b:sc_s:sc_e];');
sc3=uicontrol('style','edit','units','normalized',...
   'position',[.73 .91 .1 .04],'fontsize',10,...
   'string',num2str(sc_s),'createfcn','',...
   'callback','sc_s=str2num(get(gco,''string''));sc=[sc_b:sc_s:sc_e];');
sc4=uicontrol('style','edit','units','normalized',...
   'position',[.84 .91 .1 .04],'fontsize',10,...
   'string',num2str(sc_e),'createfcn','',...
   'callback','sc_e=str2num(get(gco,''string''));sc=[sc_b:sc_s:sc_e];');
sc1=uicontrol('style','text','units','normalized',...
   'position',[.51 .91 .1 .04],'fontsize',10,...
   'string','Scales:',...
   'createfcn','');

% row for dilations/squeezing
dl_b=.95;
dl_s=5e-2;
dl_e=1.05;
dl=[dl_b:dl_s:dl_e];
dl2=uicontrol('style','edit','units','normalized',...
   'position',[.62 .86 .1 .04],'fontsize',10,...
   'string',num2str(dl_b),'createfcn','',...
   'callback','dl_b=str2num(get(gco,''string''));dl=[dl_b:dl_s:dl_e];');
dl3=uicontrol('style','edit','units','normalized',...
   'position',[.73 .86 .1 .04],'fontsize',10,...
   'string',num2str(dl_s),'createfcn','',...
   'callback','dl_s=str2num(get(gco,''string''));dl=[dl_b:dl_s:dl_e];');
dl4=uicontrol('style','edit','units','normalized',...
   'position',[.84 .86 .1 .04],'fontsize',10,...
   'string',num2str(dl_e),'createfcn','',...
   'callback','dl_e=str2num(get(gco,''string''));dl=[dl_b:dl_s:dl_e];');
dl1=uicontrol('style','text','units','normalized',...
   'position',[.51 .86 .1 .04],'fontsize',10,...
   'string','Dilations:',...
   'createfcn','');


%%%%%%%
% added on 03.04.2005

% rows for polynomial trend in the form a+bx,
% a=0 (we'll take absolute term in the "rise/low")
%% ALL VALUES ARE IN MICRONOLTS!!!!

% for "a" first: 
As_b=-10;
As_s=5;
As_e=10;
As=[As_b:As_s:As_e];
As2=uicontrol('style','edit','units','normalized',...
   'position',[.62 .765 .1 .035],'fontsize',10,...
   'string',num2str(As_b),'createfcn','',...
   'callback','As_b=str2num(get(gco,''string''));As=[As_b:As_s:As_e];');
As3=uicontrol('style','edit','units','normalized',...
   'position',[.73 .765 .1 .035],'fontsize',10,...
   'string',num2str(As_s),'createfcn','',...
   'callback','As_s=str2num(get(gco,''string''));As=[As_b:As_s:As_e];');
As4=uicontrol('style','edit','units','normalized',...
   'position',[.84 .765 .1 .035],'fontsize',10,...
   'string',num2str(As_e),'createfcn','',...
   'callback','As_e=str2num(get(gco,''string''));As=[As_b:As_s:As_e];');
As1=uicontrol('style','text','units','normalized',...
   'position',[.51 .765 .1 .035],'fontsize',10,'fontweight','bold',...
   'string','Poly, a :',...
   'tooltip','The set for absolute term "a" in the polinomial TREND accounting in the form a+bx+cx^2.');

% for "b" : 
Bs_b=-2e-1;
Bs_s=2e-1;
Bs_e=2e-1;
Bs=[Bs_b:Bs_s:Bs_e];
Bs2=uicontrol('style','edit','units','normalized',...
  'position',[.62 .725 .1 .035],'fontsize',10,...
   'string',num2str(Bs_b),'createfcn','',...
   'callback','Bs_b=str2num(get(gco,''string''));Bs=[Bs_b:Bs_s:Bs_e];');
Bs3=uicontrol('style','edit','units','normalized',...
   'position',[.73 .725 .1 .035],'fontsize',10,...
   'string',num2str(Bs_s),'createfcn','',...
   'callback','Bs_s=str2num(get(gco,''string''));Bs=[Bs_b:Bs_s:Bs_e];');
Bs4=uicontrol('style','edit','units','normalized',...
   'position',[.84 .725 .1 .035],'fontsize',10,...
   'string',num2str(Bs_e),'createfcn','',...
   'callback','Bs_e=str2num(get(gco,''string''));Bs=[Bs_b:Bs_s:Bs_e];');
Bs1=uicontrol('style','text','units','normalized',...
   'position',[.51 .725 .1 .035],'fontsize',10,'fontweight','bold',...
   'string','Poly, b :',...
   'tooltip','The set for linear term "b" in the polinomial TREND accounting in the form a+bx+cx^2.');


%%%%%%%%%%%%%%%%

% text for query for function length
uicontrol('style','text','units','normalized',...
   'position',[.53 .60 .27 .07],'fontsize',10,...
   'string','Input the length of max waveform in the set to create =======>',...
   'createfcn','');

% input the length of function
lfs2=uicontrol('style','edit','units','normalized',...
   'position',[.81 .60 .1 .05],'fontsize',10,...
   'callback','',...
   'string','',...
   'createfcn','');

% information text
itd2=uicontrol('style','text','units','normalized','FontWeight','bold',...
   'position',[.69 .51 .3 .07],'fontsize',10,...
   'createfcn','','visible','off');

% button for starting the set forming
sfd2=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.73 .45 .26 .05],'String','Create the set',...
   'FontWeight','bold','fontsize',10,...
   'Callback',...
   'set(itd2,''ForegroundColor'',[1 0 0],''string'',''Wait for set functions to be created...'',''visible'',''on''); pause(.1); F=funsetcreation_tr(wf,str2num(get(lfs2,''string'')),sc,dl,As,Bs);set(itd2,''string'',[ num2str(size(F,1)) '' Functions are ready.''],''ForegroundColor'',[0 1 0]);[str,stb]=size(F);   str_cntr=0;    set(lchd2,''Color'',[1 0 0]);');

%text for file name with the set to open
sfot=uicontrol('style','edit','units','normalized',...
    'FontWeight','bold',...
   'position',[.505 .51 .17 .05],'fontsize',10,...
   'createfcn','');

% button for opening the set from file
uicontrol('style','pushbutton','units','normalized',...
    'FontWeight','bold',...
   'position',[.505 .45 .2 .05],'fontsize',10,...
   'createfcn','','string','Load set from file',...
   'callback',['load(get(sfot,''string''));'...
      'str_cntr=0;[str stb]=size(F);']);


% button for plotting the set functions
shsfd2=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.57 .39 .4 .05],'String','Show the functions one by one',...
   'FontWeight','bold','fontsize',10,...
   'Callback',[...
       '[str stb]=size(F);'...
       'GalileoView_scr_6;']);











% text for filename with the set functions
std2=uicontrol('Style','edit','Units','normalized',...
   'Position',[.57 .33 .3 .05],'String','',...
   'FontWeight','normal','fontsize',10,...
   'Callback','');

% button for saving the set functions in the file
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.57 .27 .3 .05],'String','Save the set',...
   'FontWeight','bold','fontsize',10,...
   'Callback','save(get(std2,''string''),''F''); ');

% button for  starting calculations of
% coefficients
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.17 .21 .6 .05],...
   'String','Start coefficients calculating.',...
   'FontWeight','bold','fontsize',10,...
   'Callback','eeg_patt_loc');

uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.17 .15 .6 .05],...
   'String','Creating concatenated waveforms.',...
   'FontWeight','bold','fontsize',10,...
   'Callback','signal_visual_1_scr_7;');

uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.17 .09 .6 .05],...
   'FontWeight','bold','fontsize',10,...
   'String','Adding the sets of functions',...
   'Callback','signal_visual_1_scr_10;');

uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.17 .03 .6 .05],...
   'FontWeight','bold','fontsize',10,...
   'String','Edit this waveform with Wave_Composer',...
'Callback',strcat(...
   'wave_composer;  ',...
   'totpts=length(wf);  ',...   
   'set(l,''ydata'',wf,''xdata'',1:totpts);',... 
   'set(a,''xtick'',[1:totpts]);',...
   'set([sld l fna sw fp],''visible'',''on'');'...
 ));




%%%%%%%%%%%%%%%%%
set(fwd2,'visible','on');
figure(fwd2);
