% Function for viewing and analysing the Galileo 200 files with EEG signals.
%
% 29.04.2005
% 27.08.2005
% 11.09.2005
% 28.04.2008 - adding the DX files from .m file
% 11.01.2009 - update the paroxismal index menu with wavelets,
%               template of background activity
% 11.01.2009 - adding the DX files from .txt files
% 09.01.2010 - added line 70 (for correct saving the data from GTF file to% MAT file)
% 13.03.2010 - filtering with saving in DX-Sys format (with script)

% 15.04.2015 - added opening and visuzlization of EEG and marks (Oleg,
% Kharitonov): menu+one additional lead


% Montages creating _scr_15
% channel labeling and arranging in _scr_1


clc;
close all
clear all
f1=figure('Name','Galileo View  4.0, BESA Group, PhBME Dept., NTUU KPI' , ...
        'NumberTitle','off', ...
        'Visible','off');
set(0,'units','normalized');
set(gcf,'units','normalized')
set(gcf,'position',[0.0020    0.0530    0.9941    0.88]); %
set(0,'units','pixels');
set(gcf,'renderer','painters');
set(gcf,'color',[0.5    0.75    0.4]);

%scaling of EEG
% for amplitude scaling of the signal.
%To obtain initially 50uV/cm we must multiply the amplitude of 50uV LABEL!!!!!!!!

%scale50in1=1.6327;% for notebook
%scale50in1=2;% for P3
scale50in1=1.25;% for my home PC
scale= scale50in1; % current scale

% time scaling !!!!!!!!!
% width of grand axes, mm. Should be set before using every PC.
%ax_len=275;% for notebook
%ax_len=245;% for P3
ax_len=339;% my home251
sec_to_see=ax_len/30;% initial time scale for 30 mm/sec
% to create montages -- use scr_15

% close button creation
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.945 .002 .05 .03],'String','Close',...
   'FontWeight','light','fontsize',12,'Callback','clear all; close(gcf)');

% text for filename with signal name 
fn1=uicontrol('style','text','units','normalized',...
   'string','',...
   'position',[.001 .959 .115 .04],'FontWeight','normal','fontsize',12,...
   'TooltipString','Type the name of Galileo file (*.GTF) with the EEG signal you want to open. Then press "Plot" button.',...
   'callback','      ','visible','off');

% button for opening the file .GTF and plotting the graph
% % % % % % % uicontrol('Style','pushbutton','Units','normalized',...
% % % % % % %    'Position',[.12 .959 .025 .04],'String','Op.1',...
% % % % % % %    'FontWeight','normal','fontsize',8,'Callback',...
% % % % % % %    ['[fname,pname] = uigetfile(''*.gtf'',''Galileo Planet 200 files Opener'');'...
% % % % % % %    'h=sopen(fname);'...
% % % % % % %       'clear A Ab; pack;'...
% % % % % % %       'A=-1*transpose(h.data);'...
% % % % % % %       'h.data=A;'...
% % % % % % %       'SampleRate=h.SampleRate;'...
% % % % % % %       'ff=sortrows([h.EVENT.POS h.EVENT.TYP-10],1);'...
% % % % % % %       'GalileoView_scr_1;'...
% % % % % % %       'set(fn1,''string'',fname);',...
% % % % % % %       'set(ulm,''string'','''');'...
% % % % % % %       'set([a1 al_l al_r scc sct ulm fn1],''visible'',''on'');'...
% % % % % % %       'set([men ment menf mencol mensp menpsp menpi],''enable'',''on'')']);
% % % % % % % 
% % % % % % % % button for opening the file .mat with matrix and plotting the graph
% % % % % % % % reused on 10.04.09
% % % % % % % % 09.01.2010 
% % % % % % % uicontrol('Style','pushbutton','Units','normalized',...
% % % % % % %    'Position',[.146 .959 .025 .04],'String','Op.2',...
% % % % % % %    'FontWeight','normal','fontsize',8,'Callback',...
% % % % % % %    ['[fname,pname] = uigetfile(''*.mat'',''EEG DX Systems files Opener'');'...
% % % % % % %    'GalileoView_scr_23']);

 
%text with lead number 
sn1=uicontrol('style','text','string','0',...
   'FontWeight','normal','fontsize',8,...
   'units','normalized',...
   'tooltipstring','The number of selected lead. Press "Show this" to plot selected signal lead in separate window.',...
   'position',[.173 .959 .025 .04]   );

% button for plotting one selected lead
plb=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.201 .959 .07 .04],'String','Show Lead',...
   'FontWeight','normal','fontsize',8,...
   'enable','inactive','Callback','GalileoView_scr_2;');

% button for direct jump to coefficients visualizing 
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.272 .959 .08 .04],'String','Coef. visual.',...
   'FontWeight','normal','fontsize',8,'Callback','coef=1:1000; eeg_patt_loc_coef_vis;');

% button for direct jump to coefficients calculating 
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.354 .959 .08 .04],'String','Coef.Calc.',...
   'FontWeight','normal','fontsize',8,'Callback','eeg_patt_loc');

% button for direct jump to adaptive function using 
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.436 .959 .08 .04],'String','Adapt.fun.',...
   'FontWeight','normal','fontsize',8,'Callback','adapted_func_1');
% button for direct jump to overcomplete set creation 
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.518 .959 .08 .04],'String','Set creation',...
   'FontWeight','normal','fontsize',8,'Callback',...
   'wf_beg=1; wf_end=10;  sig=zeros(1,10);  GalileoView_scr_5;');




% label pulses 50uV/cm
Lab=[ zeros(1,5) 50*ones(1,5) zeros(1,5) ];% labels for scale
% before 25/05/2005 :  Lab=scale50in1*[ zeros(1,5) 50*ones(1,5) zeros(1,5) ];% labels for scale

% right axis for label plot 
al_r=axes('parent',gcf);
set(al_r,'box','on','linewidth',2,'tickdir','in','ticklength',[.01 0.025],...
       'ytick',[],'xtick',[],...
   'xticklabel',[],'color',[.9 .9 1],...
   'units','normalized','visible','off');
set(al_r,'position',[.979 .091 .020 .86]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%axis for signal plot
a1=axes('parent',gcf);
set(a1,'box','on','linewidth',2,'tickdir','in','ticklength',[.01 0.025]...
    ,'units','normalized','position',[.07 .091 .909 .86]);
set(a1,'GridLineStyle',':','xgrid','on','ygrid','on',...
    'fontname','courier','fontsize',10,'FontWeight','normal',...
    'color',[1 1 1],'xcolor','black','ycolor','black',...%'color',[.95 .95 1]
    'visible','off','TickLength',[0 0],...
    'buttondownfcn','c=get(a1,''currentpoint'');');
 
 % left axis for label plot 
al_l=axes('parent',gcf);
set(al_l,'box','off','linewidth',2,'tickdir','in','ticklength',[.01 0.025],...
       'ytick',[],'xtick',[],...
   'xticklabel',[],'color','none',...%[.9 .9 1],...
   'units','normalized','visible','off');
set(al_l,'position',[.07 .091 .025 .86]);


%%%%%%%%%%%%%%%%%%%
% context menu for marking begin and end of the segment
s_beg=1;
s_end=257;
cm=uicontextmenu;

set(a1,'uicontextmenu',cm);

uimenu(cm,'position',1,'label','Begin of Segment',...
   'callback','s_beg=round(c(1,1));');
uimenu(cm,'position',2,'label','End of Segment',...
   'callback','s_end=max(s_beg+257,round(c(1,1)));');
uimenu(cm,'position',3,'label','Color change',...
   'callback','set(gcf,''color'',[rand(1,3)])');

%%%%%%%%%%%%%%%%%%%
% added 17.01.2006
% text with user label
ulm=uicontrol('style','text','string','',...
   'FontWeight','bold','fontsize',12,...
   'ForegroundColor',[1 .3 .3],...
   'BackgroundColor',[1 1 1],...
   'units','normalized',...
   'tooltipstring','Click on the star to see the associated Label',...
   'position',[.6 .959 .15 .04],'visible','off');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% menu for EEG Opening
men0=uimenu('position',1,'label','Open EEG','enable','on');
uimenu('parent',men0,'label','Open from .gtf ','callback',...
      ['[fname,pname] = uigetfile(''*.gtf'',''Galileo Planet 200 files Opener'');'...
   'h=sopen(fname);'...
      'clear A Ab; pack;'...
      'A=-1*transpose(h.data);'...
      'h.data=A;'...
      'SampleRate=h.SampleRate;'...
      'ff=sortrows([h.EVENT.POS h.EVENT.TYP-10],1);'...
      'GalileoView_scr_1;'...
      'set(fn1,''string'',fname);',...
      'set(ulm,''string'','''');'...
      'set([a1 al_l al_r scc sct ulm fn1],''visible'',''on'');'...
      'set([men ment menf mencol mensp menpsp menpi menwav],''enable'',''on'')']);

uimenu('parent',men0,'label','Open from .mat','callback',...
      ['[fname,pname] = uigetfile(''*.mat'',''EEG DX Systems files Opener'');'...
   'GalileoView_scr_23']);

uimenu('parent',men0,'label','Open from .mat + annotations','callback',...
      ['[fname,pname] = uigetfile(''*.mat'',''EEG DX Systems files Opener'');'...
   'GalileoView_scr_30']);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% menu for amplitude scaling
men=uimenu('position',2,'label','Amplitude Scaling','enable','off');
uimenu('parent',men,'label','12,5 uV/cm ','callback','scale=scale50in1*50/12.5; set(scc,''string'',[num2str(50*scale50in1/scale) '' uV/cm'']); GalileoView_scr_18; GalileoView_scr_9; ')
uimenu('parent',men,'label','25 uV/cm','callback','scale=scale50in1*50/25; set(scc,''string'',[num2str(50*scale50in1/scale) '' uV/cm'']); GalileoView_scr_18; GalileoView_scr_9; ')
uimenu('parent',men,'label','35 uV/cm','callback','scale=scale50in1*50/35; set(scc,''string'',[num2str(50*scale50in1/scale) '' uV/cm'']); GalileoView_scr_18; GalileoView_scr_9; ')
uimenu('parent',men,'label','50 uV/cm','callback','scale=scale50in1; set(scc,''string'',[num2str(50*scale50in1/scale) '' uV/cm'']); GalileoView_scr_18; GalileoView_scr_9; ')
uimenu('parent',men,'label','70 uV/cm','callback','scale=scale50in1*50/70; set(scc,''string'',[num2str(50*scale50in1/scale) '' uV/cm'']); GalileoView_scr_18; GalileoView_scr_9; ')
uimenu('parent',men,'label','100 uV/cm','callback','scale=scale50in1*50/100; set(scc,''string'',[num2str(50*scale50in1/scale) '' uV/cm'']); GalileoView_scr_18; GalileoView_scr_9; ')
uimenu('parent',men,'label','150 uV/cm','callback','scale=scale50in1*50/150; set(scc,''string'',[num2str(50*scale50in1/scale) '' uV/cm'']); GalileoView_scr_18; GalileoView_scr_9; ')
uimenu('parent',men,'label','200 uV/cm','callback','scale=scale50in1*50/200; set(scc,''string'',[num2str(50*scale50in1/scale) '' uV/cm'']); GalileoView_scr_18; GalileoView_scr_9; ')
uimenu('parent',men,'label','400 uV/cm','callback','scale=scale50in1*50/400; set(scc,''string'',[num2str(50*scale50in1/scale) '' uV/cm'']); GalileoView_scr_18; GalileoView_scr_9; ')
uimenu('parent',men,'label','Custom scale...','callback',' GalileoView_scr_11;')

%%%%%%%%%%%%%%
% text with current amplitude scale
scc=uicontrol('parent',f1,'style','text','units','normalized','position',[.001 .1 .06 .06],...
    'string',[num2str(50*scale/scale50in1) ' uV/cm'],'FontWeight','normal','fontsize',8,...
    'BackgroundColor','white','ForegroundColor','black','visible','off');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% menu for time scaling
ment=uimenu('position',3,'label','Time Scaling','enable','off');
uimenu('parent',ment,'label','7,5 mm/sec ','callback','sec_to_see=ax_len/7.5; sv=get(sss,''value''); delete(get(al_l,''children''));delete(get(al_r,''children'')); GalileoView_scr_1; set(sss,''value'',sv); set(sct,''string'',[num2str(ax_len/sec_to_see) '' mm/sec'']); GalileoView_scr_9; ')
uimenu('parent',ment,'label','15 mm/sec ','callback','sec_to_see=ax_len/15; sv=get(sss,''value''); delete(get(al_l,''children''));delete(get(al_r,''children'')); GalileoView_scr_1; set(sss,''value'',sv);  set(sct,''string'',[num2str(ax_len/sec_to_see) '' mm/sec'']);  GalileoView_scr_9; ')
uimenu('parent',ment,'label','30 mm/sec ','callback','sec_to_see=ax_len/30; sv=get(sss,''value''); delete(get(al_l,''children''));delete(get(al_r,''children'')); GalileoView_scr_1; set(sss,''value'',sv);  set(sct,''string'',[num2str(ax_len/sec_to_see) '' mm/sec'']); GalileoView_scr_9; ')
uimenu('parent',ment,'label','60 mm/sec ','callback','sec_to_see=ax_len/60; sv=get(sss,''value''); delete(get(al_l,''children''));delete(get(al_r,''children'')); GalileoView_scr_1; set(sss,''value'',sv);  set(sct,''string'',[num2str(ax_len/sec_to_see) '' mm/sec'']); GalileoView_scr_9; ')
uimenu('parent',ment,'label','120 mm/sec ','callback','sec_to_see=ax_len/120; sv=get(sss,''value''); delete(get(al_l,''children''));delete(get(al_r,''children'')); GalileoView_scr_1; set(sss,''value'',sv);  set(sct,''string'',[num2str(ax_len/sec_to_see) '' mm/sec'']); GalileoView_scr_9; ')


%%%%%%%%%%%%%%
% text with current time scale
sct=uicontrol('parent',f1,'style','text','units','normalized','position',[.001 .04 .06 .06],...
    'string',[num2str(ax_len/sec_to_see) ' mm/sec'],'FontWeight','normal','fontsize',8,...
    'BackgroundColor','white','ForegroundColor','black','visible','off');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% filtering menu
menf=uimenu('position',4,'label','Filtering','enable','off');
uimenu('parent',menf,'label','Filter Design',...
    'callback',['set(res,''enable'',''on'');'...
        'Filter_composer;']);
uimenu('parent',menf,'label','Custom Filter of entire signal',...
    'callback',['set(res,''enable'',''on'');'...
        'Ab=A;'...
        'GalileoView_scr_16;']);
uimenu('parent',menf,'label','Custom Filter of segment',...
    'callback',['set(res,''enable'',''on'');'...
        'Ab=A;'...
        'B=A(:,s_beg:s_end);'...
        'GalileoView_scr_17;'...
        '']);
uimenu('parent',menf,'label','Save current EEG signal in .mat format',...
    'callback',['Ab=A;'...
        '[filename,pathname,x] = uiputfile(''*.mat'',''Save current EEG signal as...'');'...
        'h.data=A;'...
        'save(filename,''h'');'...
        '']);

res=uimenu('parent',menf,...
    'label','Restore Initial Signal ',...
    'enable','off',...
    'callback',['A=Ab; clear Ab;'...
       'set(res,''enable'',''off'');'...
       'GalileoView_scr_9;']);
 
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% WAVELET MENU!!!! 19.03.2006
% 04.02.2010, added complexes localization by CWT
% 29.05.2010
menwav=uimenu('position',5,'label','Wavelets','enable','off');
uimenu('parent',menwav,'label','Process the Signal',...
    'callback',['set(respi,''enable'',''on'');'...
        'Ab=A;'...
        ''...
        'GalileoView_scr_24;'...
        '']);
uimenu('parent',menwav,'label','Remove underlining',...
    'callback',['wl=-1000*ones(1,size(A,2));'...
               'GalileoView_scr_9;'...
        '']);
    
    
% uimenu('parent',menpi,'label','Process Signal with Wavelets',...
%     'callback',['set(respi,''enable'',''on'');'...
%         'Ab=A;'...
%         ''...
%         'GalileoView_scr_21;'...
%         '']);
% uimenu('parent',menwav,'label','Use as Template of Background Activity',...
%     'callback',['set(respi,''enable'',''on'');'...
%         'Ab=A;'...
%         'bckgrnd_act=A(:,s_beg:s_end);'...
%         ''...
%         '']);
reswav=uimenu('parent',menwav,...
    'label','Restore Initial Signal ',...
    'enable','off',...
    'callback',['A=Ab; clear Ab; '...
       'pl=-1000*ones(1,smp_num);'...
       'GalileoView_scr_9; '...
       'set(respi,''enable'',''off'');']);



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% spectral analysis menu 25.11.2006
mensp=uimenu('position',6,'label','Spectral Functions','enable','off');

uimenu('parent',mensp,'label','Periodogram of selected lead',...
    'callback',[''...
        'figure;'...
        '[bbb,fff]=pwelch(A(ln,s_beg:s_end),[],[],[],h.SampleRate);'...
        'disp(fff);'...
        'plot(fff(1:260),bbb(1:260));'...
        'set(gca,''xtick'',[2 4 8 14 40]);'...
        'clear bbb fff;'...%title(strcat(''Power Spectral Density of .'', get(sn1,''string''), '' lead.''));
        'xlabel(''F, Hz'');'...
        'ylabel(''PSD, V^2/Hz'');'...
        'grid on;'...
        '']);%GalileoView_scr_19; - it was here  
    
  uimenu('parent',mensp,'label','Spectrogram of selected lead',...
    'callback',[''...
        'figure;'...
        'specgram(A(ln,s_beg:s_end),h.SampleRate,h.SampleRate,[]);'...
        'title(strcat(''Spectrogram of .'', get(sn1,''string''), '' lead,   dB''));'...
        'set(gca,''xticklabel'',str2num(get(gca,''xticklabel''))+round(s_beg/256));'...
        'xlabel(''t, sec'');'...
        'ylabel(''Hz'');'...
        'colorbar;'...
        '']);
  uimenu('parent',mensp,'label','FFT of selected lead',...
    'callback',[''...
        'figure;'...
        'sp=2*abs(fft(A(ln,s_beg:s_end)/(s_end-s_beg+1)));'...
        'fff=linspace(0,h.SampleRate-1,length(sp));'...
        'plot(fff(1:1000),sp(1:1000));'...
        'set(gca,''xtick'',[2 4 8 14 40]);'...
        'clear sp fff;'...%title(strcat(''Power Spectral Density of .'', get(sn1,''string''), '' lead.''));
        'xlabel(''F, Hz'');'...
        'ylabel(''PSD, V^2/Hz'');'...
        'grid on;'...
        '']);
    
        
%set(gca,''xticklabel'',str2num(get(gca,''xticklabel''))+s_beg/256);
%        'figure;'...
%        '[bbb,fff,ttt]=specgram(A(ln,s_beg:s_end),256,256,[]);'...
%        'imagesc(ttt+s_beg/256,fff,20*log10(abs(bbb)));set(gca,''ydir'',''reverse'');'...
%        'colorbar;'...



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% POLYspectral analysis menu 27.11.2006
menpsp=uimenu('position',7,'label','POLYSpectral Functions','enable','off');

uimenu('parent',menpsp,'label','Bispectrum Estimation',...
    'callback',[''...
        'figure;'...
        '[bbb,fff]=bispeci(A(ln,s_beg:s_end),30);'...
        '%plot(fff(1:40),bbb(1:40));'...
        '%set(gca,''xtick'',[1 4 8 14 40]);'...
        '%clear bbb fff; title(strcat(''Power Spectral Density of .'', get(sn1,''string''), '' lead.''));'...
        '%xlabel(''Hz'');'...
        '%ylabel(''Volts^2/sqrt(Hz)'');'...
        '%grid on;'...
        'figure; surf(abs(bbb));']);  
  
  %'figure; surf(abs(bbb));']);  

  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% paroxysmal index analysis menu 09.03.2007
% 11.01.2009 - added the possibility to make template of background EEG activity for
% paroxismal index

menpi=uimenu('position',8,'label','Paroxysmal Index','enable','off');

uimenu('parent',menpi,'label','Process Signal with Averaging',...
    'callback',['set(respi,''enable'',''on'');'...
        'Ab=A;'...
        ''...
        'GalileoView_scr_20;'...
        '']);
uimenu('parent',menpi,'label','Process Signal with Wavelets',...
    'callback',['set(respi,''enable'',''on'');'...
        'Ab=A;'...
        ''...
        'GalileoView_scr_21;'...
        '']);
uimenu('parent',menpi,'label','Use as Template of Background Activity',...
    'callback',['set(respi,''enable'',''on'');'...
        'Ab=A;'...
        'bckgrnd_act=A(:,s_beg:s_end);'...
        ''...
        '']);
    
respi=uimenu('parent',menpi,...
    'label','Restore Initial Signal ',...
    'enable','off',...
    'callback',['A=Ab; clear Ab; '...
       'pl=-1000*ones(1,smp_num);'...
       'GalileoView_scr_9; '...
       'set(respi,''enable'',''off'');']);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% colouring menu
mencol=uimenu('position',9,'label','Color','enable','off');
uimenu('parent',mencol,'label','Mark Red','callback',['set(l,''color'',[1 0 0]);']);
uimenu('parent',mencol,'label','Mark Yellow','callback',['set(l,''color'',[.9 .85 0]);']);
uimenu('parent',mencol,'label','Mark Green','callback',['set(l,''color'',[0 .85 0]);']);
uimenu('parent',mencol,'label','Mark Blue','callback',['set(l,''color'',[0 0 1]);']);
uimenu('parent',mencol,'label','Mark Black','callback',['set(l,''color'',[0 0 0]);']);
uimenu('parent',mencol,'label','All Black','callback',['set(l_hnd,''color'',[0 0 0]);']);
uimenu('parent',mencol,'label','Set Style Black&Green',...
   'callback',...
   ['set(a1,''color'',[0 0 0]);'...
      'set(f1,''color'',''black'');'...
      'set(a1,''xcolor'',[.7 .5 0]);'...
      'set(a1,''ycolor'',[.7 .5 0]);'...
      'set(l_hnd,''color'',[0 1 0]);']);
uimenu('parent',mencol,'label','Set Style Initial',...
   'callback',...
   ['set(a1,''color'',[.95 .95 1]);'...
      'set(f1,''color'',[0.5    0.75    0.4]);'...
      'set(a1,''xcolor'',[0 0 0]);'...
      'set(a1,''ycolor'',[0 0 0]);'...
      'set(l_hnd,''color'',[0 0 0]);']);

%%%%%%%%%%%%
set(gcf,'visible','on');
figure(f1);
