%script #13 for GalileoView
% 
% called from GalileoView
%  
% opens new figure for setting the frequencies
% then performs low-pass filtering of the signal (entire)
% 30.06.2005 9-28

% LOW PASS!!!
figure('Name','Cut-off Frequency for Low-Pass filtering', ...
        'NumberTitle','off','units','normalized','position',[0.15    0.6    0.25    0.2],...
        'color',[0.803    0.5485    0.2618]);
% edit for frequency input
newscale=uicontrol('style','edit','units','normalized',...
   'position',[.1 .7 .4 .2],'FontWeight','normal','fontsize',14,...
   'TooltipString','Type the frequency  and press "Update" button.',...
   'callback','',...
   'string','20');


% button for updating the frequency, filtering
% and closing the figure
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.1 .45 .4 .2],'String','Update',...
   'FontWeight','light','fontsize',14,...
   'Callback',...
   strcat('fr=str2num(get(newscale,''string''));',...
   '[N,Wn] = buttord(fr/(.5*SampleRate), (fr+.5)/(.5*SampleRate), 3, 20);',...
   '[bb,aa]=butter(N,Wn);' ,...
       'GalileoView_scr_12;',...
       'GalileoView_scr_9;',...
       'clear newscale; ',...
       'close(gcf);'));
