%script #3 for GalileoView
% called from GalileoView_scr_2
% called after slider on detailed plot is moved
% 26.05.2005 17-49
beg=round(get(ssd1,'value')/time_step+1);
en=beg+sig_show_step_d;
if en>smp_num
   en=smp_num;
   beg=en-sig_show_step_d;
end
ld1=line('parent',ad1,'linewidth',1);
set(ld1,'ydata',sig(beg:en),...
   'xdata',beg:en,...
   'buttondownfcn',...
   'C=get(ad1,''currentpoint'');set(snd1,''string'',num2str(round(C(1,1))) );',...
   'userdata','');
set(ad1,'xlim',[beg en],'xtick',beg:SampleRate:en,...
   'xticklabel',[beg-1:SampleRate:en]*time_step,...
   'ylim',ax_lims,...
   'buttondownfcn',...
   'C=get(ad1,''currentpoint'');set(snd1,''string'',num2str(round(C(1,1))) );',...
   'userdata','');