% script # 7 for signal_visualization program
% allows to concatenate two waveforms from given two
% sets in one waveform
% 4-10-2004 21-09

% ie recalled from _scr_5

% updated 7.10.2004, adding the rises/lowings to concatenated
% waveforms in the set -- by _scr_8


fc2=figure('Name','Concatenating waveforms.', ...
        'NumberTitle','off', ...
        'Visible','off');
     set(fc2,'units','pixels');
     s=get(0,'ScreenSize');
set(fc2,'position',[.1*s(3) .07*s(4) .8*s(3) .8*s(4)]);
set(fc2,'doublebuffer','on');
set(fc2,'renderer','painters');
set(fc2,'color',[.8  .9 .1]);
clear s;

% close button creation
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.9 .005 .09 .07],'String','Close',...
   'FontWeight','bold','fontsize',10,'Callback','close(gcf)');

% file1 name
fnc1=uicontrol('style','edit','units','normalized',...
   'position',[.01 .89 .1 .04],'fontsize',10,...
   'string','');
% button for opening first part
ob1=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.01 .84 .1 .04],'String','Open',...
   'FontWeight','bold','fontsize',10,...
   'Callback','load(get(fnc1,''string'')); P1=F; clear F;');

% file2 name
fnc2=uicontrol('style','edit','units','normalized',...
   'position',[.12 .89 .1 .04],'fontsize',10,...
   'string','');
% button for opening second part
ob2=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.12 .84 .1 .04],'String','Open',...
   'FontWeight','bold','fontsize',10,...
   'Callback','load(get(fnc2,''string'')); P2=F; clear F;');

% button for concatenating
cb3=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.01 .79 .4 .04],'String','Concatenate the sets',...
   'FontWeight','bold','fontsize',10,...
   'Callback','waveform_concat_1;');

% button for giving the set a rises/lowings
cb4=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.01 .74 .7 .04],'String','Add "equal for both" rising/lowing to waveforms on the set.',...
   'FontWeight','bold','fontsize',10,...
   'Callback','set([okb h11 h12 h13 h14 rs11 rs12 rs13 rs14],''visible'',''on'')');

% Headers for parameter description
h11=uicontrol('style','text','units','normalized',...
   'position',[.1 .69 .1 .03],'fontsize',10,...
   'string','Parameter','visible','off');
h12=uicontrol('style','text','units','normalized',...
   'position',[.21 .69 .1 .03],'fontsize',10,...
   'string','Min value','visible','off');
h13=uicontrol('style','text','units','normalized',...
   'position',[.32 .69 .1 .03],'fontsize',10,...
   'string','Step','visible','off');
h14=uicontrol('style','text','units','normalized',...
   'position',[.43 .69 .1 .03],'fontsize',10,...
   'string','Max value','visible','off');
% row for rising/lowing
rs_ba=-.5;
rs_sa=5e-2;
rs_ea=.5;
rsa=[rs_ba:rs_sa:rs_ea];
rs12=uicontrol('style','edit','units','normalized','visible','off',...
   'position',[.21 .64 .1 .04],'fontsize',10,...
   'string',num2str(rs_b),'createfcn','',...
   'callback','rs_ba=str2num(get(gco,''string''));rsa=[rs_ba:rs_sa:rs_ea];');
rs13=uicontrol('style','edit','units','normalized','visible','off',...
   'position',[.32 .64 .1 .04],'fontsize',10,...
   'string',num2str(rs_s),'createfcn','',...
   'callback','rs_sa=str2num(get(gco,''string''));rsa=[rs_ba:rs_sa:rs_ea];');
rs14=uicontrol('style','edit','units','normalized','visible','off',...
   'position',[.43 .64 .1 .04],'fontsize',10,...
   'string',num2str(rs_e),'createfcn','',...
   'callback','rs_ea=str2num(get(gco,''string''));rsa=[rs_ba:rs_sa:rs_ea];');
rs11=uicontrol('style','text','units','normalized','visible','off',...
   'position',[.1 .64 .1 .04],'fontsize',10,...
   'string','Rises:',...
   'createfcn','');

% "OK" button for adding
okb=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.1 .59 .3 .04],'String','Modify the functions',...
   'FontWeight','bold','fontsize',10,'visible','off',...
   'Callback','signal_visual_1_scr_8;');

% text with number of functions obtained
nft=uicontrol('Style','text','Units','normalized',...
   'Position',[.1 .52 .6 .04],'String','','visible','off',...
   'FontWeight','bold','fontsize',10,...
   'Callback','');


% text for file name to save the waveset
fnt2=uicontrol('Style','edit','Units','normalized',...
   'Position',[.01 .45 .21 .04],'String','',...
   'FontWeight','bold','fontsize',10,...
   'Callback','');

% saving the new obtained waveform set
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.01 .4 .21 .04],'String','Save',...
   'FontWeight','bold','fontsize',10,...
   'Callback','save(get(fnt2,''string''), ''F'');');

%%%%%%%%%%%%%
set(fc2,'visible','on')
