% script # 10 for signal_visualization program
% allows to add two sets of functions in one
% essentially, we open two files with matrix, create one 
% larger matrix
% 12-12-2004 9-54

% is recalled from _scr_5


fa2=figure('Name','Adding two sets of functions into one.', ...
        'NumberTitle','off', ...
        'Visible','off');
     set(fa2,'units','pixels');
     s=get(0,'ScreenSize');
set(fa2,'position',[.1*s(3) .07*s(4) .8*s(3) .8*s(4)]);
set(fa2,'doublebuffer','on');
set(fa2,'renderer','painters');
set(fa2,'color',[.8 .9 .7]);
clear s;

% close button creation
fa2cb=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.9 .005 .09 .07],'String','Close',...
   'FontWeight','bold','fontsize',10,'Callback','close(gcf)');

% file1 name
fnc1=uicontrol('style','edit','units','normalized',...
   'position',[.01 .89 .1 .04],'fontsize',10,...
   'string','');
% button for opening first part
ob1=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.01 .84 .1 .04],'String','Open',...
   'FontWeight','bold','fontsize',10,...
   'Callback','load(get(fnc1,''string'')); P1=F; clear F;');

% file2 name
fnc2=uicontrol('style','edit','units','normalized',...
   'position',[.12 .89 .1 .04],'fontsize',10,...
   'string','');
% button for opening second part
ob2=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.12 .84 .1 .04],'String','Open',...
   'FontWeight','bold','fontsize',10,...
   'Callback','load(get(fnc2,''string'')); P2=F; clear F;');

% button for adding the sets
cb3=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.01 .79 .4 .04],'String','Add these sets',...
   'FontWeight','bold','fontsize',10,...
   'Callback',...
   '[p1r,p1c]=size(P1);[p2r,p2c]=size(P2);pcma=max(p1c,p2c); F=zeros(p1r+p2r,pcma); F(1:p1r,1:p1c)=P1;F(p1r+1:p1r+p2r,1:p2c)=P2; clear P1 P2 p1r p2r p1c p2c pcma;');

% text for file name to save the waveset
fnt2=uicontrol('Style','edit','Units','normalized',...
   'Position',[.01 .45 .21 .04],'String','',...
   'FontWeight','bold','fontsize',10,...
   'Callback','');

% saving the new obtained waveform set
snfb2=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.01 .4 .21 .04],'String','Save',...
   'FontWeight','bold','fontsize',10,...
   'Callback','save(get(fnt2,''string''), ''F'');');

%%%%%%%%%%%%%
set(fa2,'visible','on')
