% script # 4 for signal_visualization program
% plots the selected lead signal in the new figure
% detailed plot of lead part, after SLIDER moved
% called from _scr_3

beg=floor( get(ssd1,'value')*siglen )+1;
en=beg+show_step;
if en>siglen
   en=siglen;
   beg=en-show_step;
end
ld1=line('parent',ad1,'linewidth',2);
set(ld1,'ydata',sig(beg:beg+show_step),...
   'xdata',beg:en,...
   'buttondownfcn',...
   'C=get(ad1,''currentpoint'');set(snd1,''string'',num2str(round(C(1,1))) );',...
   'userdata','');

% repaired 23.11.2004
set(ad1,'xtickmode','manual',...
   'xlim',[beg en],'xtick',linspace(beg,en,7),...
   'xlimmode','manual',...
   'ylim',[min(sig)-.1 max(sig)+.1],...
   'buttondownfcn',...
   'C=get(ad1,''currentpoint'');set(snd1,''string'',num2str(round(C(1,1))) );',...
   'userdata','',...
   'xticklabel',(linspace(beg,en,7)-1)*time_step*dsr);

%set(ad1,'xlim',[beg en],'xtick',[beg:floor(show_step/10):beg+show_step],...
%   'ylim',[min(sig)-.1 max(sig)+.1],...
%   'buttondownfcn',...
%   'C=get(ad1,''currentpoint'');set(snd1,''string'',num2str(round(C(1,1))) );',...
%   'userdata','');
