% program for viewing multichannel signal, stored in file
% (eeg1_full, eeg2_full) 
% 23.09.2004 13-48

% updated 7.10.2004, added button for direct jump to forming
% the set (in _scr_5 ) using the function

% updated 08.03.2005 cleared and added the button for coef. visualizing

%close all
%clear all
f1=figure('Name','Visualizing  EEG signal from file.', ...
        'NumberTitle','off', ...
        'Visible','off');
     set(f1,'units','pixels');
     s=get(0,'ScreenSize');
set(f1,'position',[.01*s(3) .05*s(4) .98*s(3) .88*s(4)]);
set(f1,'doublebuffer','off');
set(f1,'renderer','painters');
set(f1,'color',[.5  .75 .5]);
clear s;

% close button creation
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.9 .005 .09 .04],'String','Close',...
   'FontWeight','bold','fontsize',14,'Callback','close(gcf)');

%% text with tip for signal name typing
%sn1=uicontrol('Style','text','Units','normalized',...
%   'Position',[.005 .952 .12 .045],'String','The name of file with signal =>',...
%   'FontWeight','bold','fontsize',8,'buttondownfcn','','visible','off');

% text for filename with signal name 
fn1=uicontrol('style','edit','units','normalized',...
   'position',[.005 .952 .12 .045],'FontWeight','normal','fontsize',12,...
   'TooltipString','Type the name of file with the EEG signal you want to open. Then press "Plot" button.',...
   'callback','');

% button for plotting the graph
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.126 .952 .05 .045],'String','Plot',...
   'FontWeight','bold','fontsize',10,'Callback','clear signmatr ; signmatr=get(fn1,''string''); load(signmatr); signal_visual_1_scr_1; set(a1,''visible'',''on'')');

%%tip text with lead number 
%ssp1=uicontrol('Style','text','Units','normalized',...
%   'Position',[.33 .952 .05 .045],'String','Lead ====>',...
%   'FontWeight','bold','fontsize',9,'buttondownfcn','');

%text with lead number 
sn1=uicontrol('style','text','string','0',...
   'FontWeight','bold','fontsize',12,...
   'units','normalized',...
   'tooltipstring','The number of selected lead. Press "Show this" to plot selected signal lead in separate window.',...
   'position',[.177 .952 .03 .045]   );

% button for plotting one selected lead
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.208 .952 .1 .045],'String','Show This',...
   'FontWeight','bold','fontsize',10,'Callback','signal_visual_1_scr_3');


% button for direct jump to coefficients visualizing 
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.31 .952 .15 .045],'String','Coef. visual.',...
   'FontWeight','bold','fontsize',8,'Callback','coef=1:1000; coef_visual;');
% button for direct jump to adaptive function using 
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.55 .952 .15 .045],'String','Adaptive function',...
   'FontWeight','bold','fontsize',8,'Callback','adapted_func_1');
% button for direct jump to overcomplete set creation 
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.71 .952 .15 .045],'String','Set creation',...
   'FontWeight','bold','fontsize',8,'Callback','wf_beg=1; wf_end=10;  sig=zeros(1,10);  signal_visual_1_scr_5 ');
% button for direct jump to coefficients calculating 
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.87 .952 .12 .045],'String','Coefficients',...
   'FontWeight','bold','fontsize',8,'Callback','coef_calcul_1;');



%axis for signal plot
a1=axes('parent',f1);
set(a1,'box','on','linewidth',2,'tickdir','in','ticklength',[.01 0.025]...
    ,'units','normalized','position',[.055 .091 .92 .855]);
set(a1,'GridLineStyle',':','xgrid','on','ygrid','on',...
    'fontname','courier','fontsize',10,'FontWeight','bold',...
    'color',[.9 .9 1],'xcolor','black','ycolor','black',...
    'buttondownfcn','','visible','off');
 
%%%%%%%%%%%%
set(f1,'visible','on');
%figure(f1);
