% program for manual constructing
% the waveforms for further EEG analysis
% #1 3.10.2004 17-29

%updated on 10.03.2005

f=figure('Name','Manual waveform composer.', ...
        'NumberTitle','off','Visible','on');
     set(f,'units','pixels');
     s=get(0,'ScreenSize');
set(f,'position',[s(1) .05*s(4) .995*s(3) .88*s(4)]);
set(f,'doublebuffer','on');
set(f,'renderer','painters');
set(f,'color',[.7  .8 .5]);

% close button creation
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.9 .005 .09 .04],'String','Close',...
   'FontWeight','bold','fontsize',14,'Callback','close(gcf)');

% text with tip for number of points typing
sn=uicontrol('Style','text','Units','normalized',...
   'Position',[.003 .967 .28 .028],'String',...
   'Input the number of points in the waveform =>',...
   'FontWeight','normal','fontsize',8,'buttondownfcn','');

% text for number of points 
fn=uicontrol('style','edit','units','normalized',...
   'position',[.285 .96 .05 .038],'FontWeight','normal','fontsize',8,...
   'callback','');

% button for making the "zero line template"
uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.34 .96 .05 .038],'String','Make',...
   'FontWeight','bold','fontsize',14,'Callback',strcat(...
                'set([sld l fna sw fp],''visible'',''on''); ',...
                ' totpts=str2num(get(fn,''string''));',...
                '  set(l,''ydata'',zeros(1,totpts),''xdata'',1:totpts);',...
                'set(a,''xtick'',[1:totpts]);'...
               ));

% textbox containing the coordinates of current cursor
% position
cp=uicontrol('style','text','string',...
   int2str(1),'units','normalized','position',[.4 .96 .05 .038],...
   'FontWeight','normal','fontsize',10);

%axis for waveform plot
a=axes('parent',f);
set(a,'box','on','linewidth',3,'tickdir','in','ticklength',[.01 0.025]...
    ,'units','normalized','position',[.045 .13 .6 .8]);
set(a,'GridLineStyle',':','XGrid','on','YGrid','on',...
    'fontname','courier','fontsize',5,'FontWeight','bold',...
    'color',[.9 .9 1],'xcolor','black','ycolor','black','ytick',[-1:.2:1],'ylim',[-1 1],...
    'YLimMode','manual');

%making the line "without line"
l=line('parent',a,'linewidth',2, 'buttondownfcn' ,...
    '   D=get(a,''currentpoint''); set(cp,''string'',num2str(round(D(1,1))) );    ',...
    'visible','off','marker','.','markersize',35);

 % slider for detailed plot
sld=uicontrol('Style','slider','Units','normalized','Position',[.66 .37 .04 .35],'max',1,'min',-1, ...
   'SliderStep',[0.01 0.1],'visible','off',...
   'tooltip','Move the slider to rise/low current point of waveform. ',...
'callback',strcat(...
    'wave=get(l,''ydata'');',...
    'wave(str2num(get(cp,''string'')))=wave(str2num(get(cp,''string'')))+get(sld,''value'');',...
    'set(l,''ydata'',wave); ',...
    'set(gco,''value'',0);'...
));

% file name
fna=uicontrol('style','edit','string','',...
   'units','normalized','position',[.702 .79 .13 .05],...
   'FontWeight','normal','fontsize',10,...
   'visible','off',...
   'tooltip','Input the name of file for this waveform.');

% button for saving obtained waveform
sw=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.702 .73 .2 .05],'String','Save the function',...
   'FontWeight','bold','fontsize',10,'visible','off',...
   'Callback','save(get(fna,''string''), ''wave'');');

% button for further processing the signal with
% obtained waveform
fp=uicontrol('Style','pushbutton','Units','normalized',...
   'Position',[.72 .61 .26 .05],'String','Create the function set.',...
   'FontWeight','bold','fontsize',10,'visible','off',...
   'Callback','sig=wave/max(abs(wave)); wf_beg=1; wf_end=totpts; clear wave; signal_visual_1_scr_5;');
